name: Build and Push Docker Images
on:
  push:
    branches:
      - main
      - docker
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      gitsha: ""
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: get git sha
        # id: vars
        run: echo "gitsha=$(git rev-parse --short=8 HEAD)" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/arm64/v8,linux/amd64
          push: true
          tags: ghcr.io/paulchen5/ba-latex-template:latest,ghcr.io/paulchen5/ba-latex-template:${{ env.gitsha }}
